### ISSUE TITLE
default value

### ISSUE THREAD

**Issue by OVyazovoy** [konstantin-nizhinskiy/I18n#8]
Hi, can you please make a default value for i18n. Some key or just text, it will be not bad, thx!

**Comment by OVyazovoy** [comment]
Hi, can you please make a default value for i18n. Some key or just text, it will be not bad, thx!

**Comment by konstantin-nizhinskiy** [comment]
in version v1.1.0
    i18n.setProperty({
        locale: 'EN', // location on
        localeDefault: 'EN', //locale on default if key of main locale is empty
        versionJson: '1.1.1', // versionJson add to url params load file translation
        defaultValue: '' // You can set default value for translated
    });

and you can set defaultValue in getter

   var demoFunction=function(){
            console.log(i18n.get("test.test.test")); // Test test test
            console.log(i18n.get("count.books", {count: 20}));  // 20 books
            console.log(i18n.get("book.name.pages.number", {name: 'JS', number: 201})); // Book JS page 201
            console.log(i18n.get("test.test.test1")); // test.test.test1
            console.log(i18n.get("test.test.test1",{},{defaultValue:'my value'})); // my value
        };
